# Generated by Django 3.2.3 on 2023-05-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='edge',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='experience',
            field=models.IntegerField(blank=True, default=1000),
        ),
    ]
