# Generated by Django 3.2.3 on 2023-05-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mech',
            name='stock',
        ),
        migrations.AlterField(
            model_name='mech',
            name='record_sheet',
            field=models.CharField(default='custom', max_length=50),
        ),
    ]
