# Generated by Django 3.2.3 on 2023-05-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activemech',
            name='mech',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_pilot', to='webapp.mech'),
        ),
    ]
