# Generated by Django 3.2.3 on 2023-05-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20230508_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mech',
            old_name='pilots',
            new_name='pilot',
        ),
        migrations.AlterField(
            model_name='pilot',
            name='callsign',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
