# Generated by Django 3.2.3 on 2023-05-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_activemech_mech'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemech',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Available'), (1, 'Available')], default=0),
        ),
    ]
